#!/bin/bash

# author: Paolo Fagni
green='\e[0;32m'
GREEN='\e[1;32m'
red='\e[0;31m'
RED='\e[1;31m'
blue='\e[0;34m'
BLUE='\e[1;34m'
cyan='\e[0;36m'
CYAN='\e[1;36m'
NC='\e[0m' # No Color
#Common checks for docker related scripts

# Check if docker is installed
if ! [ -x "$(command -v docker)" ]; then
  echo -e '${RED}Error: Docker is not installed or you do not have the rights to run it.${NC}' >&2
  exit 1
fi


#Check if container name is provided
if [ -z "$1" ]
then
  echo -e "You need to provide the container name (or part of it)  as an argument to this script."
  echo -e "${CYAN}Example: <command> my-container${NC}"
  echo -e "${CYAN}The default container name if you did not change it is pff2web${NC}"
  exit 1
else
  CONTAINER_NAME=$1
fi

# Find the SHA of the running container
CONTAINER_SHA=$(docker ps -q -f name=$CONTAINER_NAME)

# Check if container is running
if [ -z "$CONTAINER_SHA" ]
then
  echo "No running container found with name: $CONTAINER_NAME"
  exit 1
fi

